# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  style:
    name: Performing stylecheck
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup python
        uses: actions/setup-python@v1
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install black
        run: |
          echo "Installing app"
          pipenv install black
      - name: Check style
        run: |
          echo "Running stylecheck using black"
          pipenv run black -t py38 --check bot/
          
